![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# Pandas Series exercises

In [2]:
# Import the numpy package under the name np
import numpy as np

# Import the pandas package under the name pd
import pandas as pd

# Print the pandas version and the configuration
print(pd.__version__)

2.2.2

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series creation

### Create an empty pandas Series

In [3]:
# your code goes here
pd.Series()

Series([], dtype: object)

In [4]:
pd.Series()

Series([], dtype: object)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y pandas Series

In [6]:
# your code goes here
X = ['k', 'r', 'y', 's']
Y = pd.Series(X)
print(X, type(X))
print(Y, type(Y))

['k', 'r', 'y', 's'] <class 'list'>
0    k
1    r
2    y
3    s
dtype: object <class 'pandas.core.series.Series'>

In [5]:
X = ['A','B','C']
print(X, type(X))

Y = pd.Series(X)
print(Y, type(Y)) # different type

['A', 'B', 'C'] <class 'list'>
0    A
1    B
2    C
dtype: object <class 'pandas.core.series.Series'>

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, name it 'My letters'

In [9]:
# your code goes here
X = ['a', 'b', 'c']
Y = pd.Series(X)
Y.name = 'My letters'
Y

0    a
1    b
2    c
Name: My letters, dtype: object

In [8]:
X = pd.Series(['A','B','C'])

X.name = 'My letters'
X

0    A
1    B
2    C
Name: My letters, dtype: object

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show its values

In [ ]:
# your code goes here

In [10]:
X = pd.Series(['A','B','C'])

X.values

array(['A', 'B', 'C'], dtype=object)

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series indexation

### Assign index names to the given X pandas Series

In [ ]:
# your code goes here

In [11]:
X = pd.Series(['A','B','C'])
index_names = ['first', 'second', 'third']

X.index = index_names
X

first     A
second    B
third     C
dtype: object

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show its first element

In [ ]:
# your code goes here

In [13]:
X = pd.Series(['A','B','C'], index=['first', 'second', 'third'])

#X[0] # by position
#X.iloc[0] # by position
X['first'] # by index

/tmp/ipython-input-13-4035588154.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  X[0] # by position

'A'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show its last element

In [ ]:
# your code goes here

In [14]:
X = pd.Series(['A','B','C'], index=['first', 'second', 'third'])

#X[-1] # by position
#X.iloc[-1] # by position
X['third'] # by index

'C'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show all middle elements

In [ ]:
# your code goes here

In [15]:
X = pd.Series(['A','B','C','D','E'],
              index=['first','second','third','forth','fifth'])

#X[['second', 'third', 'forth']]
#X.iloc[1:-1] # by position
X[1:-1] # by position

second    B
third     C
forth     D
dtype: object

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the elements in reverse position

In [ ]:
# your code goes here

In [17]:
X = pd.Series(['A','B','C','D','E'],
              index=['first','second','third','forth','fifth'])

#X.iloc[::-1]
X[::-1]

fifth     E
forth     D
third     C
second    B
first     A
dtype: object

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the first and last elements

In [ ]:
# your code goes here

In [18]:
X = pd.Series(['A','B','C','D','E'],
              index=['first','second','third','forth','fifth'])

#X[['first', 'fifth']]
#X.iloc[[0, -1]]
X[[0, -1]]

/tmp/ipython-input-18-1500303121.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  X[[0, -1]]

first    A
fifth    E
dtype: object

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series manipulation

### Convert the given integer pandas Series to float

In [ ]:
# your code goes here

In [ ]:
X = pd.Series([1,2,3,4,5],
              index=['first','second','third','forth','fifth'])

pd.Series(X, dtype=np.float)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given pandas Series (first element becomes last)

In [ ]:
# your code goes here

In [19]:
X = pd.Series([1,2,3,4,5],
              index=['first','second','third','forth','fifth'])

X[::-1]

fifth     5
forth     4
third     3
second    2
first     1
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given pandas Series

In [ ]:
# your code goes here

In [20]:
X = pd.Series([4,2,5,1,3],
              index=['forth','second','fifth','first','third'])

X = X.sort_values()
X

first     1
second    2
third     3
forth     4
fifth     5
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, set the fifth element equal to 10

In [ ]:
# your code goes here

In [21]:
X = pd.Series([1,2,3,4,5],
              index=['A','B','C','D','E'])

X[4] = 10
X

/tmp/ipython-input-21-4063770036.py:4: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  X[4] = 10

A     1
B     2
C     3
D     4
E    10
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, change all the middle elements to 0

In [ ]:
# your code goes here

In [ ]:
X = pd.Series([1,2,3,4,5],
              index=['A','B','C','D','E'])

X[1:-1] = 0
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, add 5 to every element

In [ ]:
# your code goes here

In [ ]:
X = pd.Series([1,2,3,4,5])

X + 5

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series boolean arrays (also called masks)

### Given the X pandas Series, make a mask showing negative elements

In [ ]:
# your code goes here

In [ ]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get the negative elements

In [ ]:
# your code goes here

In [ ]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
X[mask]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get numbers higher than 5

In [ ]:
# your code goes here

In [ ]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = X > 5
X[mask]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get numbers higher than the elements mean

In [ ]:
# your code goes here

In [ ]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = X > X.mean()
X[mask]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get numbers equal to 2 or 10

In [ ]:
# your code goes here

In [ ]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = (X == 2) | (X == 10)
X[mask]

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions

### Given the X pandas Series, return True if none of its elements is zero

In [ ]:
# your code goes here

In [ ]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

X.all()

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, return True if any of its elements is zero

In [ ]:
# your code goes here

In [ ]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

X.any()

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X pandas Series, show the sum of its elements

In [ ]:
# your code goes here

In [ ]:
X = pd.Series([3,5,6,7,2,3,4,9,4])

#np.sum(X)
X.sum()

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the mean value of its elements

In [ ]:
# your code goes here

In [ ]:
X = pd.Series([1,2,0,4,5,6,0,0,9,10])

#np.mean(X)
X.mean()

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the max value of its elements

In [ ]:
# your code goes here

In [ ]:
X = pd.Series([1,2,0,4,5,6,0,0,9,10])

#np.max(X)
X.max()

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)